# Generated by Django 5.1.6 on 2025-02-06 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField(null=True, verbose_name='Start Date')),
                ('enddate', models.DateField(null=True, verbose_name='End Date')),
                ('leavetype', models.CharField(choices=[('full day', 'Full Day'), ('half day', 'Half Day')], default='None', max_length=25)),
                ('leave_category', models.CharField(blank=True, choices=[('sick leave', 'Sick Leave'), ('earned leave', 'Earned Leave'), ('casual leave', 'Casual Leave'), ('loss of pay', 'Loss of Pay'), ('work from home', 'Work From Home'), ('emergency leave', 'Emergency Leave'), ('morning session', 'Morning Session'), ('afternoon session', 'Afternoon Session')], default='None', max_length=20, null=True)),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('reason', models.CharField(blank=True, help_text='Add additional information for leave', max_length=255, null=True, verbose_name='Reason for Leave')),
                ('defaultdays', models.PositiveIntegerField(blank=True, default=25, null=True, verbose_name='Leave days per year counter')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('is_approved', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('half_day', models.BooleanField(default=False)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave',
                'verbose_name_plural': 'Leaves',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sick_leave', models.IntegerField(default=3)),
                ('annual_leave', models.IntegerField(default=3)),
                ('casual_leave', models.IntegerField(default=3)),
                ('emergency_leave', models.IntegerField(default=3)),
                ('earned_leave', models.IntegerField(default=3)),
                ('loss_of_pay', models.IntegerField(default=5)),
                ('work_from_home', models.IntegerField(default=5)),
                ('used_sick_leave', models.IntegerField(default=0)),
                ('used_annual_leave', models.IntegerField(default=0)),
                ('used_casual_leave', models.IntegerField(default=0)),
                ('used_emergency_leave', models.IntegerField(default=0)),
                ('used_earned_leave', models.IntegerField(default=0)),
                ('used_loss_of_pay', models.IntegerField(default=0)),
                ('used_work_from_home', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
